### ISSUE TITLE
We are unable to find the constructor declaration corresponding to new BugInCF(postfixTree + " is not in postfixLookup")

### ISSUE THREAD

**Issue by jonathan-m-phillips** [njit-jerse/specimin#283]
While running ASHE in dryrun mode, the following exception was produced.

--outputDirectory "/my/temp/dir" --root "/my/root/checker-framework/dataflow/src/main/java" --targetFile "org/checkerframework/dataflow/analysis/AnalysisResult.java" --targetMethod "org.checkerframework.dataflow.analysis.AnalysisResult#getPostfixBinaryTree(UnaryTree)"

> Task :run FAILED
Exception in thread "main" UnsolvedSymbolException{context='null', name='We are unable to find the constructor declaration corresponding to new BugInCF(postfixTree + " is not in postfixLookup")', cause='null'}
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:188)
	at com.github.javaparser.ast.expr.ObjectCreationExpr.resolve(ObjectCreationExpr.java:369)
	at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:606)
	at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:52)
	at com.github.javaparser.ast.expr.ObjectCreationExpr.accept(ObjectCreationExpr.java:114)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:940)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:53)
	at com.github.javaparser.ast.stmt.ThrowStmt.accept(ThrowStmt.java:74)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1133)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:53)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1172)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:171)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:53)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:72)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:556)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:53)
	at com.github.javaparser.ast.stmt.IfStmt.accept(IfStmt.java:84)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1133)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:53)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1172)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:171)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:53)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:72)
	at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$60(ModifierVisitor.java:674)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:674)
	at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:444)
	at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:52)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:103)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1133)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:53)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1172)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:246)
	at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:277)
	at org.checkerframework.specimin.TargetMethodFinderVisitor.visit(TargetMethodFinderVisitor.java:52)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:97)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1133)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:53)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1172)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:310)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:53)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:126)
	at org.checkerframework.specimin.SpeciminRunner.performMinimizationImpl(SpeciminRunner.java:336)
	at org.checkerframework.specimin.SpeciminRunner.performMinimization(SpeciminRunner.java:126)
	at org.checkerframework.specimin.SpeciminRunner.main(SpeciminRunner.java:83)

FAILURE: Build failed with an exception.

**Comment by kelloggm** [comment]
I can't reproduce this with the given example.

> Edit: This is happening in multiple places on Checker Framework.

Do you have some of the others handy? I can try to see if I can reproduce the problem using them, instead.

**Comment by kelloggm** [comment]
> I can't reproduce this with the given example.
> 
> > Edit: This is happening in multiple places on Checker Framework.
> 
> Do you have some of the others handy? I can try to see if I can reproduce the problem using them, instead.

@jonathan-m-phillips ping on this - I'd like to get to the bottom of this problem, but I can't reproduce it with the given example
