### ISSUE TITLE
Crashes with "qualifiedNameToFilePath only works for classes in the original directory" on java.util.concurrent.TimeUnit

### ISSUE THREAD

**Issue by gmerr3** [njit-jerse/specimin#361]
Command:
```
./gradlew run --args="--outputDirectory \"./tmp\" --root \"$(pwd)\" --targetFile \"Scheduler.java\" --targetMethod \"Scheduler#schedule(Runnable, int)\"" --info --stacktrace
```
Code(Scheduler.java):
```
import static java.util.concurrent.Executors.newSingleThreadScheduledExecutor;

import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class Scheduler{
	public static final ScheduledExecutorService s = newSingleThreadScheduledExecutor(x -> new Thread(x, "scheduler thread"));

	private Scheduler() {

	}

	public static void schedule(Runnable task, int delay) {
		s.schedule(task, delay, TimeUnit.MILLISECONDS);
	}
}
```

Stack trace:
```
Exception in thread "main" java.lang.RuntimeException: qualifiedNameToFilePath only works for classes in the original directory
at org.checkerframework.specimin.UnsolvedSymbolVisitor.qualifiedNameToFilePath(UnsolvedSymbolVisitor.java:1567)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.updatedAddedTargetFilesForPotentialEnum(UnsolvedSymbolVisitor.java:1591)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:1073)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:105)
        at com.github.javaparser.ast.expr.FieldAccessExpr.accept(FieldAccessExpr.java:95)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1111)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:52)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1149)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:642)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:1212)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:105)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:135)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:475)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:52)
        at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:72)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1111)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:52)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1149)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:166)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:774)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:105)
        at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:71)
        at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$60(ModifierVisitor.java:661)
        at java.base/java.util.Optional.map(Optional.java:260)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:661)
        at org.checkerframework.specimin.SpeciminStateVisitor.visit(SpeciminStateVisitor.java:187)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.processMethodDeclaration(UnsolvedSymbolVisitor.java:2123)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:1045)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:105)
        at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:195)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1111)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:52)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1149)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:239)
        at org.checkerframework.specimin.SpeciminStateVisitor.visit(SpeciminStateVisitor.java:216)
        at org.checkerframework.specimin.SpeciminStateVisitor.visit(SpeciminStateVisitor.java:33)
        at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:152)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1111)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:52)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1149)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:307)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:52)
        at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:134)
        at org.checkerframework.specimin.SpeciminRunner.performMinimizationImpl(SpeciminRunner.java:301)
        at org.checkerframework.specimin.SpeciminRunner.performMinimization(SpeciminRunner.java:163)
        at org.checkerframework.specimin.SpeciminRunner.main(SpeciminRunner.java:90)
```
Adding a print statement shows that the class it is attempting to resolve is java.util.concurrent.TimeUnit.

**Comment by gmerr3** [comment]
fixed in #371
