### ISSUE TITLE
Crash with IllegalArgumentException given records

### ISSUE THREAD

**Issue by gmerr3** [njit-jerse/specimin#365]
code:
```
public class Test {

    R r = new R("h");
    public record R(String a) {

    }

    public String A(String param) {
        return r.a();
    }
}
```
command:
```
./gradlew run --args="--outputDirectory \"/tmp/specimin4772587264303907278\" --root \"/home/user/test/src/java/\" --targetFile \"test/Test.java\" --targetMethod \"test.Test#A(String)\""
```
output:
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot get a reference type declaration from com.github.javaparser.ast.body.RecordDeclaration
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.toTypeDeclaration(JavaSymbolSolver.java:461)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeDeclaration(JavaParserFacade.java:746)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:90)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:100)
        at com.github.javaparser.resolution.Context.solveTypeInParentContext(Context.java:149)
        at com.github.javaparser.resolution.Context.solveType(Context.java:115)
        at com.github.javaparser.resolution.Context.solveType(Context.java:91)
        at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:356)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:648)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:659)
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:427)
        at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:336)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:879)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:105)
        at com.github.javaparser.ast.body.VariableDeclarator.accept(VariableDeclarator.java:153)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1111)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:52)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1149)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:501)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:1001)
        at org.checkerframework.specimin.UnsolvedSymbolVisitor.visit(UnsolvedSymbolVisitor.java:105)
        at com.github.javaparser.ast.body.FieldDeclaration.accept(FieldDeclaration.java:126)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1111)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:52)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1149)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:239)
        at org.checkerframework.specimin.SpeciminStateVisitor.visit(SpeciminStateVisitor.java:216)
        at org.checkerframework.specimin.SpeciminStateVisitor.visit(SpeciminStateVisitor.java:33)
        at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:152)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1111)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:52)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1149)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:307)
        at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:52)
        at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:134)
        at org.checkerframework.specimin.SpeciminRunner.performMinimizationImpl(SpeciminRunner.java:301)
        at org.checkerframework.specimin.SpeciminRunner.performMinimization(SpeciminRunner.java:163)
        at org.checkerframework.specimin.SpeciminRunner.main(SpeciminRunner.java:90)
```
A similar bug is reported as a bug in JavaParser(https://github.com/javaparser/javaparser/issues/4303) but seems to have been closed as fixed in 3.26.0(this project uses 3.26.1). Updating to 3.26.2 gives this error on basically anything:
```
/home/user/specimin2/specimin/src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java:792: error: incompatible types: Type cannot be converted to ReferenceType
      referenceType = patternExpr.getType();
```

**Comment by kelloggm** [comment]
> Updating to 3.26.2 gives this error on basically anything:

I fixed those problems in #357, but I haven't merged it because it causes ~5% of the methods in plume-util to go from compilable to not compilable for some reason, and I've been distracted and haven't prioritized investigating why. You could check if this issue with records goes away if you run it on that branch; if so, that's a good reason to prioritize getting #357 merged.

**Comment by kelloggm** [comment]
Record support was added in #461.
