### ISSUE TITLE
Deletes input source files under some circumstances

### ISSUE THREAD

**Issue by gmerr3** [njit-jerse/specimin#368]
File 1(A.java):
```
import java.io.IOException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.nio.channels.AsynchronousSocketChannel;

public class A{
	public AsynchronousSocketChannel client;
	public A(AsynchronousSocketChannel client){
		this.client=client;
	}
	public InetAddress test(){
		try {
			if(client.getRemoteAddress() instanceof InetSocketAddress isa)
				return isa.getAddress();
		} catch (IOException e) {
			
		}
		return null;
	}
}
```
File 2(B.java):
```

import java.io.IOException;
import java.net.InetAddress;

public class B extends A {

    @Override
    public InetAddress test(){
        return super.test();
    }
}
```
Command:
```
gradlew run  --args="--outputDirectory \"/tmp/specimin328479325\" --root \"/path/to/src/main/java\" --targetFile \"B.java\" --targetMethod \"B#test()\""
```
The source file A.java is deleted when running the above command.
It is deleted at this point:
```
at org.checkerframework.specimin.UnsolvedSymbolVisitor.deleteOldSyntheticClass(UnsolvedSymbolVisitor.java:3201)
at org.checkerframework.specimin.UnsolvedSymbolVisitor.updateSyntheticSourceCode(UnsolvedSymbolVisitor.java:3182)
at org.checkerframework.specimin.SpeciminRunner.performMinimizationImpl(SpeciminRunner.java:303)
at org.checkerframework.specimin.SpeciminRunner.performMinimization(SpeciminRunner.java:163)
at org.checkerframework.specimin.SpeciminRunner.main(SpeciminRunner.java:90)
```

**Comment by gmerr3** [comment]
fixed in #371
